title: Just Cause+
author:
  name: Jonathan Ma
  email: 'justcausehk@gmail.com'
metadata:
    description: '﻿﻿​A university-student-run start-up providing professional consulting services to Social Enterprises & NGOs.'

# Site settings
title: Just Cause+
email: justcausehk@gmail.com
description: "﻿﻿​The official site of Just Cause+, a university-student-run start-up providing professional consulting services to Social Enterprises & NGOs."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - label: Facebook
    url: "#"
    icon: facebook
  - label: Google+
    url: "mail:justcausehk@gmail.com"
    icon: google-plus

copyright:
  line1: Just Cause+ 2016
  line2: Design:
  url: http://ihome.ust.hk/~jcema
  url_label: JohnMa

logo:
  text1: "Just Cause+"
  text2: "Just because we care."

# Submenu
submenu:
  - text: "Dolore Sed"
    link: "#"
  - text: "Consequat"
    link: "#"
  - text: "Lorem Magna"
    link: "#"
  - text: "Sed Magna"
    link: "#"
  - text: "Ipsum Nisl"
    link: "#"

buttons:
  - text: "Make Appointment"
    link: "#"
